//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileCabinetApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileCabinetApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available commands:.
        /// </summary>
        internal static string AvailableCommandsMessage {
            get {
                return ResourceManager.GetString("AvailableCommandsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget (with currency sign): .
        /// </summary>
        internal static string BudgetEnteringRequest {
            get {
                return ResourceManager.GetString("BudgetEnteringRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth: .
        /// </summary>
        internal static string DateOfBirthEnteringRequest {
            get {
                return ResourceManager.GetString("DateOfBirthEnteringRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting an application....
        /// </summary>
        internal static string ExitingMessage {
            get {
                return ResourceManager.GetString("ExitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name: .
        /// </summary>
        internal static string FirstNameEnteringRequest {
            get {
                return ResourceManager.GetString("FirstNameEnteringRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your command, or enter &apos;help&apos; to get help..
        /// </summary>
        internal static string GetHelpHint {
            get {
                return ResourceManager.GetString("GetHelpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Cabinet Application, developed by {0}.
        /// </summary>
        internal static string GreetingMessage {
            get {
                return ResourceManager.GetString("GreetingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	{0}	- {1}.
        /// </summary>
        internal static string HelpCommandDescriptionLine {
            get {
                return ResourceManager.GetString("HelpCommandDescriptionLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no &apos;{0}&apos; command..
        /// </summary>
        internal static string InvalidCommandMessage {
            get {
                return ResourceManager.GetString("InvalidCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID..
        /// </summary>
        internal static string InvalidIDMessage {
            get {
                return ResourceManager.GetString("InvalidIDMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no {0} property. Type &apos;help find&apos; for further information..
        /// </summary>
        internal static string InvalidPropertyMessage {
            get {
                return ResourceManager.GetString("InvalidPropertyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value to search for must be in double quotes (find [PROPERTY] &quot;&lt;YourValue&gt;&quot;)..
        /// </summary>
        internal static string InvalidValueToSearchMessage {
            get {
                return ResourceManager.GetString("InvalidValueToSearchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids count: .
        /// </summary>
        internal static string KidsCountEnteringRequest {
            get {
                return ResourceManager.GetString("KidsCountEnteringRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name: .
        /// </summary>
        internal static string LastNameEnteringRequest {
            get {
                return ResourceManager.GetString("LastNameEnteringRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no records..
        /// </summary>
        internal static string NoRecordsMessage {
            get {
                return ResourceManager.GetString("NoRecordsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is invalid..
        /// </summary>
        internal static string ParameterIsInvalidMessage {
            get {
                return ResourceManager.GetString("ParameterIsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is negative..
        /// </summary>
        internal static string ParameterIsNegativeMessage {
            get {
                return ResourceManager.GetString("ParameterIsNegativeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is null..
        /// </summary>
        internal static string ParameterIsNullMessage {
            get {
                return ResourceManager.GetString("ParameterIsNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0}, {1}, {2}, {3}, {4}, has {5} kids, budget : {6}{7}.
        /// </summary>
        internal static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no record with such value of the {0} property..
        /// </summary>
        internal static string PropertyValueNotFoundMessage {
            get {
                return ResourceManager.GetString("PropertyValueNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record #{0} is created. .
        /// </summary>
        internal static string RecordCreated {
            get {
                return ResourceManager.GetString("RecordCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record #{0} is not found..
        /// </summary>
        internal static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} records..
        /// </summary>
        internal static string RecordsCountMessage {
            get {
                return ResourceManager.GetString("RecordsCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record #{0} is updated..
        /// </summary>
        internal static string RecordUpdated {
            get {
                return ResourceManager.GetString("RecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex: .
        /// </summary>
        internal static string SexEnteringRequest {
            get {
                return ResourceManager.GetString("SexEnteringRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is null, empty or consists only of white-space characters..
        /// </summary>
        internal static string StringIsNullOrWhiteSpaceMessage {
            get {
                return ResourceManager.GetString("StringIsNullOrWhiteSpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; .
        /// </summary>
        internal static string TypeCommandSign {
            get {
                return ResourceManager.GetString("TypeCommandSign", resourceCulture);
            }
        }
    }
}
